services:
  ansible-control:
    build:
      context: .
      dockerfile: Dockerfile.control
    container_name: ansible-control
    volumes:
      - .:/ansible
      - ./ssh_keys/id_rsa:/root/.ssh/id_rsa:ro
    depends_on:
      - app-server-01
      - app-server-02
    networks:
      - ansible-net
    working_dir: /ansible

  app-server-01:
    build:
      context: .
      dockerfile: Dockerfile.ssh-host
    container_name: ansible-app-server-01
    hostname: app-server-01
    volumes:
      - ./ssh_keys/id_rsa.pub:/tmp/authorized_keys_src:ro
    networks:
      - ansible-net

  app-server-02:
    build:
      context: .
      dockerfile: Dockerfile.ssh-host
    container_name: ansible-app-server-02
    hostname: app-server-02
    volumes:
      - ./ssh_keys/id_rsa.pub:/tmp/authorized_keys_src:ro
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge
