services:
  ansible-control:
    build:
      context: .
      dockerfile: Dockerfile.control
    container_name: ansible-control
    volumes:
      - .:/ansible
    networks:
      - ansible-net
    working_dir: /ansible

  app-server-01:
    build:
      context: .
      dockerfile: Dockerfile.ssh-host
    container_name: ansible-app-server-01
    hostname: app-server-01
    volumes:
      - ./ssh_keys:/tmp/ssh_keys:ro
    networks:
      - ansible-net

  app-server-02:
    build:
      context: .
      dockerfile: Dockerfile.ssh-host
    container_name: ansible-app-server-02
    hostname: app-server-02
    volumes:
      - ./ssh_keys:/tmp/ssh_keys:ro
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge
