[app_servers]
app-server-01 ansible_host=10.0.0.1
app-server-02 ansible_host=10.0.0.2

[all:vars]
ansible_user={{ SSH_USER }}
ansible_ssh_private_key_file=~/.ssh/prod_id_rsa
ansible_python_interpreter=/usr/bin/python3
# ansible_user is injected by GitHub Actions via -e flag
